pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building Spring Boot App"
                sh './mvnw clean package'
            }
        }

        stage('Test') {
            steps {
                echo "Running Tests"
                sh './mvnw test'
            }
        }

        stage('Done') {
            steps {
                echo "Build Finished!"
            }
        }
    }
}
